### ISSUE TITLE
CRL data update

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#213]
### Description:

Add remaining data for CRL - microarray expression currently in quarantine and has missing symbols

GDrive: https://drive.google.com/drive/folders/1oHHSI7GkJ92Q3h1apHtQ3eYpXxNj-XZv

Jira ticket [PDXI-792](https://www.ebi.ac.uk/panda/jira/browse/PDXI-792)

### Acceptance criteria:

- [x] missing symbols are resolved
- [x] microarray data validated and loaded

**Comment by zperova** [comment]
Some data has symbols - we can load what is available 
those without the symbols require data model change to support locations rather than symbols

**Comment by Afollet** [comment]
The description for the if Human Genome U133 Plus 2.0 Array describes that the array is based on a 2001 UniGene Build. Therefore, it should not be expected that all of these probe locations map to HUGO genes because of the instability and potential inaccuracy of UniGene Build.

Currently there are 4 308 027 missing HUGO symbols in the set. 258 275 uniq probe id's are responsible for those data points.[Uploading... uniqMissingSymbolProbes.txt ]

I'll try looking these up with the R Bioconductor package "hgu133plus2.db"

**Comment by Afollet** [comment]
I am building the lookup file . I would surmise I can retrieve a portion of this set once this is accomplished.

**Comment by zperova** [comment]
Carried over to the next sprint due to holidays

**Comment by Afollet** [comment]
Hugo gene symbols for the set have lost fidelity since they are 15+ years old. 

Strategy to conclude work:

First generate the chromosome, start and end position for every probe for whole datasets. These three columns should be reconsider in CNA and Expression templates to express these should reflect the probe design. This is on GRCh37.

Second, update gene symbols. This is problematic. Some of the probe regions have shifted and no longer contain any genes or overlap on multiple genes. This is a problem with our dependency on HUGO gene nomenclature. For CNA and Expression. For CNA and Expression chromosome, start, and end position paired with a defined reference assembly may be more stable.

The strategy I will take is to leave rows with multiple genes or no genes as is. Therefore, the data set may still have a very large set of unloadable data points but this is a problem with the updog.

**Comment by zperova** [comment]
There is value in loading as much data as available however a caveat of the original symbols not corresponding to the updated locations in this particular scenario. Taken this into account, this data will remain quarantined until the locations are checked against the current symbols and updated. For the upcoming release, EurOPDX data is a priority, so we have agreed that @Afollet will work on this if time permits.

**Comment by Afollet** [comment]
I did a test on about 250 probes from this set and tested them against the transcription start and stop queried using genes and gene predictions from RefSeq (via UCSC Table Browser). Only 6 of the approximate 250 were not within one of the start or end of the genes transcripts. However, on brief inspection they did overlap the gene partially. These can lead to ambiguity. 

I would estimate about 528 000 ( by proportion of sample) are effected by potentially ambiguous gene symbols. This is on top of the 4 308 027 data points that do not have gene symbols (see above).



[https://app.zenhub.com/files/78657127/b69e061d-f731-44b9-b087-8cbe07c043bd/download](https://app.zenhub.com/files/78657127/b69e061d-f731-44b9-b087-8cbe07c043bd/download)

**Comment by Afollet** [comment]
Generating probe information on whole set. I will then omit the blank rows and leave the "decayed" symbols in the set and publish. The "decayed" symbols seem to overlap or be juxtaposed to their intended gene, so I see minimal harm in pushing theses ATM.

**Comment by Afollet** [comment]
Everything is cleaned. Will push to dev overnight.

**Comment by Afollet** [comment]
There is a duplicated model ID in the CRL metadata: CRL-2533-subrenal

Perhaps this should be another low priority ticket.

**Comment by Afollet** [comment]
@zperova Done.

ticket for future work to reload rows that were filtered out because they were missing HGNC symbols #325

**Comment by zperova** [comment]
thanks @Afollet
