### ISSUE TITLE
Load LIH data - EurOPDX

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#276]
### Description

Original ticket: Jira ticket [PDXI-847](https://www.ebi.ac.uk/panda/jira/browse/PDXI-847?workflowName=jira&stepId=3)

any data questions/data load issues contact Anna: https://drive.google.com/file/d/1DbHLZdVlxkxZN2WHrCPwyfReIrFVS4UR/view?usp=sharing

### Acceptance criteria:

- [x] Metadata sample molecular data validated and loaded

- [x] Cytogenetics validated and loaded

- [x] Mutation data validated and loaded

- [x] CNA data validated and loaded

- [x] Patient treatment data validated and loaded

**Comment by CsabaHalmagyi** [comment]
The link points to the metadata file only, I don't see any mutation/cna etc files. This is blocked.

**Comment by zperova** [comment]
@CsabaHalmagyi use this link please: https://drive.google.com/drive/folders/1hw8xWtgpobLSex-INeeAnr0lR8INDnDS

**Comment by CsabaHalmagyi** [comment]
In the LIH sample platform file the last few entries may need correction. 
It says: 
Molchar type: mutation
Platform: Norlux IHC
Platform type: Immunohistochemistry

This needs to be checked with the provider as I am not sure immunohistochemistry can be used for mutations. Shouldn't this be cytogenetics instead of mutation? @zperova

**Comment by CsabaHalmagyi** [comment]
Patient treatment data loaded fine.

**Comment by CsabaHalmagyi** [comment]
Mutation file issues:
Not clear what should be in coding_sequence_change	amino_acid_change columns since an extra column was inserted due to splice variant. I skipped the data from these two columns. Amino acid changes are usually short strings like G12D and not NM_007313:p.Ala1057Val

The rest of the data loaded fine.

**Comment by zperova** [comment]
Moving to the next sprint

**Comment by Afollet** [comment]
I cleaned the CNA data: removed quotes in first row. Removed new line character in first row. Removed second "example line". Deleted lines with only tabs.

I attached a list of the commands I used @CsabaHalmagyi  [https://app.zenhub.com/files/78657127/0f12ff69-dc6d-41f2-9bbf-12a7d40ccf22/download](https://app.zenhub.com/files/78657127/0f12ff69-dc6d-41f2-9bbf-12a7d40ccf22/download)

**Comment by CsabaHalmagyi** [comment]
Thanks @Afollet 
There are some extra empty columns after the platform column that makes the loading fail. Do you remember how those extra columns were removed in the past?

**Comment by Afollet** [comment]
I check all of the platform columns to see they are the same: cut -f 23 * | sort | uniq -c
Because all of the platform values are "Agilent aCGH" they can be used as a reliable anchor
Then substitute all the tabs for nothing inplace: sed -E -i 's/Agilent aCGH**.+**/Agilent aCGH/g' *
Check to be sure they are removed using grep: grep -Eo 'Agilent aCGH.*' * | cat -A | sort | uniq -c

**Comment by CsabaHalmagyi** [comment]
Loaded and validated cna.

**Comment by CsabaHalmagyi** [comment]
I looked at the mutation file and in some rows the amino_acid_change value is empty. Is this expected, @Afollet ? This will cause issues when creating the projection for the search.

**Comment by Afollet** [comment]
Looking at the data there are many intron_variants, downstream_gene_variants, and a few non_coding_transcript_variant. I would not be surprised that these do not  have amino_acid_change. The set is full of "atypical" consequences. Let me double check.

**Comment by Afollet** [comment]
@CsabaHalmagyi  When I query on Dev : 

`match (m:MolecularCharacterization)--(:Sample)--(mod:ModelCreation) return m.type, count(m.type), mod.dataSource`

LIH has a Molecular Characterization type of "copy number alterations" with an "s" which should be omitted. However, I cannot find where anywhere in the data set that is written with the "s".

Can you confirm this is correct, Csaba?

**Comment by CsabaHalmagyi** [comment]
This was present in the sampleplatform file. I think I already renamed those to copy number alteration.

**Comment by CsabaHalmagyi** [comment]
Loaded cytogenetics, it all looks fine.

**Comment by CsabaHalmagyi** [comment]
LIH data loading done.

**Comment by zperova** [comment]
Thanks @CsabaHalmagyi
