### ISSUE TITLE
Incorrect publication associated with UMCG models

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#473]
**Describe the bug**
Wrong publication associated with UMCG models: 
https://www.pdxfinder.org/data/search?datasource=UMCG

**To Reproduce**
1. Go to https://www.pdxfinder.org/data/pdx/UMCG/UMCGOVPDX84

**Expected behavior**
Correct publication: 
Biobanking of patient and patient-derived xenograft ovarian tumour tissue: efficient preservation with low and high fetal calf serum based methods.
Alkema NG, Tomar T, Duiker EW, Jan Meersma G, Klip H, van der Zee AG, Wisman GB, de Jong S.
Sci Rep. 2015 Oct 6;5:14495. doi: 10.1038/srep14495.
PMID: 26440065

**Screenshots**

![Screenshot 2021-01-11 at 14 09 35](https://user-images.githubusercontent.com/38244059/104192409-b190c280-5416-11eb-963c-7644d1d5fe0a.png)

**Comment by CsabaHalmagyi** [comment]
This is unfortunately a complex issue and I won't be able to quickfix it. The data was loaded fine and the pubmed id value is correct in our db. This bug is caused by the Publication service.
The service is using the EuropePMC api to query publications and the search for the given publication returns multiple results:

https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=26440065&resultType=core&format=json

Our service then picks the first and displays it on the website (the correct publication in this case is the last one in the resultset).

**Comment by zperova** [comment]
@CsabaHalmagyi thank you for looking into this. Pubmed ID should be unique for a publication, if EuropePMC picks up multiple articles, does this mean that there is an error on their side? Could you let them know, please to get this resolved. There might be other instances, not just this one.

**Comment by CsabaHalmagyi** [comment]
Investigating the api possibilities.

**Comment by CsabaHalmagyi** [comment]
Okay I actually found a way to patch this. Pushing a quickfix to beta.

**Comment by zperova** [comment]
great, thanks @CsabaHalmagyi

**Comment by CsabaHalmagyi** [comment]
I pushed a fix for the publication service to beta:
http://beta.pdxfinder.org/data/pdx/UMCG/UMCGOVPDX84

Waiting for the green light for this to be pushed to production. @zperova

**Comment by zperova** [comment]
green light!

**Comment by zperova** [comment]
done
