### ISSUE TITLE
Inconsistent number of EuroPDX models

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#501]
**Describe the bug**
PDX Finder displays a different number of EurOPDX models depending on the filering option.

**To Reproduce**
1. Go to PDX FInder
2. Click on Project "EurOPDX"
3. See that there is 1007 models
4. Reset filters
5. Select all the Datasources manually in Datasource filter
6. Observe result 1010 models

**Expected behavior**
Both filters produce the same result. 

**Screenshots**
![Screenshot 2021-02-08 at 14 13 26](https://user-images.githubusercontent.com/38244059/107231441-3a038280-6a18-11eb-8439-2bea7491b8ac.png)

![Screenshot 2021-02-08 at 14 13 40](https://user-images.githubusercontent.com/38244059/107231470-3ff96380-6a18-11eb-867e-27dc07d700b3.png)

**Comment by zperova** [comment]
Looks like the following models are not assigned to the EurOPDX project:
![Screenshot 2021-02-08 at 15.42.00.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/c3c573d3-c400-4603-a815-ab157464134f)

**Comment by Afollet** [comment]
Csaba fixed this in November in commit: 31b534798985ee295821dad680fc4453ef67e836

When we release data to production the problem will be resolved.

You can check this by filtering on production for EurOPDX and then searching on of the missing models. On production you will get no results. On Dev you will get results.

This was due to the "project" column on the "sharing" tab in the metadata.xlsx not being filled out correctly.

**Comment by Afollet** [comment]
@zperova done

**Comment by zperova** [comment]
Perfect! Thanks!
