### ISSUE TITLE
Fix DFCI tumour type values in the metadata template

### ISSUE THREAD

**Issue by zperova** [PDXFinder/pdxfinder#670]
**Describe the bug**

**To Reproduce**
1. Go to Admin UI
2. Click on Curation
3. Click on DFCI
4. See Tumour type

**Expected behavior**
Tumour types are only of allowed values.

**Screenshots**
![Screenshot 2021-06-01 at 10.18.24.png](https://images.zenhubusercontent.com/5b631938e115f66327ad7ac6/f09ab8d8-e973-42aa-9b1f-8a7946292a0d)

**Comment by Afollet** [comment]
@zperova  weren't you in correspondence to resolve  "Recurrent Secondary" and "Recurrent Primary". Did you get a resolution to this? To me, these primary and metastatic are covariant to recurrent and relapse. I am not sure why a tumour has to be exclusively recurrent or primary/secondary and not both.

Although, I supposed that is a dialogue for another time. 

In regards to "Not Specified". These are values that are here because of historical reasons. If you want to me to update these values, we can. However, there are going to be many more mappings.  I'll have to go in and manually fix all of the mappings here. 

But, for now, you are okay to map "Not Specified"

**Comment by Afollet** [comment]
I am emailing to resolve "Newly diagnosed" as well.

**Comment by Afollet** [comment]
I updated the mappings. There are no longer any Recurrent Primary, Recurrent Secondary or Newly Diagnosed

**Comment by Afollet** [comment]
Done
